# Generated by Django 5.2.7 on 2025-11-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('publisher', models.CharField(default='Unknow', max_length=1024)),
                ('rating', models.SmallIntegerField(default=0)),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(default='images/default.png', upload_to='images/')),
            ],
        ),
    ]
