# Generated by Django 5.2.7 on 2025-11-26 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0003_alter_game_publisher_alter_game_rating_review'),
        ('Publishers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Publishers.publisher'),
        ),
    ]
